RECIPES_INPUT_DIRECTORY = ""
TAGS_INPUT_DIRECTORIES = []
DEFAULT_NAMESPACE = "minecraft"
DEFAULT_TAG_PREFIX = f"#{DEFAULT_NAMESPACE}:"
SUPPORTED_TAG_PREFIXES = [DEFAULT_TAG_PREFIX]

ANALYSIS_PATH = ""
MERGED_JSON_FILE = f"{ANALYSIS_PATH}/recipes_original.json"
ID_JSON_FILE = f"{ANALYSIS_PATH}/config.json"
FINAL_JSON_FILE = f"{ANALYSIS_PATH}/recipes.json"
TAG_JSON_FILE = f"{ANALYSIS_PATH}/tags.json"